### ISSUE TITLE
Saving best_no_inliers and ransac loop

### ISSUE THREAD

**Issue by jorgemiar** [vigneshrajap/poly_nav#1]
Hi, 
I was looking at the code after reading the paper but was wondering why `best_no_inliers` is reset to 0 in L147:

https://github.com/vigneshrajap/poly_nav/blob/28db7e604b05ea82224ed960a0fdf83665532ce9/thorvald_2d_nav/src/poly_nav_row_following.cpp#L140-L148

Doesn't that overwrite the value you had previously saved a couple of lines earlier (L141) before doing another line_detection iteration, so you're always comparing total_pts to 0 in L111? Or am I missing something? Shouldn't `best_no_inliers` be reset when a line has been found?

https://github.com/vigneshrajap/poly_nav/blob/28db7e604b05ea82224ed960a0fdf83665532ce9/thorvald_2d_nav/src/poly_nav_row_following.cpp#L111

Also, why isn't the part below outside the ransac/line_detection for loop, are the scan points not the same for every ransac loop? That way s_pt doesn't have to be reset in L145 either.

https://github.com/vigneshrajap/poly_nav/blob/28db7e604b05ea82224ed960a0fdf83665532ce9/thorvald_2d_nav/src/poly_nav_row_following.cpp#L74-L83

Thanks 😊

**Comment by vigneshrajap** [comment]
The idea of that function is to find "two lines" using RANSAC, so I repeat the whole k (100) iterations of RANSAC two times if you notice. You see "both_lines_found" parameter.

About "best_no_inliers" part, it is reset to zero outside the loop for detecting the best fit of the second line.

That's true, scan points are the same for every ransac loop. But it is reset to zero for estimating one more line otherwise "scan_pts_index_array" will run out of memory and create segmentation fault.

I see that scan points into X,Y and theta is the same for detecting both lines. They can be done only one time somehow. Then "s_pt" is not needed.

Overall, follow the "jfr" branch. That's the last time, the code was used. The code is quite brute forced and can be improved a lot. I guess you managed to got the core idea of this code. You can improve it by reducing the parameters that are introduced to obtain this particular pattern. Good luck.

**Comment by jorgemiar** [comment]
> The idea of that function is to find "two lines" using RANSAC, so I repeat the whole k (100) iterations of RANSAC two times if you notice. You see "both_lines_found" parameter.

Yes, got that.

> About "best_no_inliers" part, it is reset to zero outside the loop for detecting the best fit of the second line.

But is it not being reset inside the RANSAC loop, due to where it is placed? The `}` that ends the RANSAC for loop is placed right below `best_no_inliers`, so at every iteration, it is reset to 0 instead of keeping the previous best value.

> Overall, follow the "jfr" branch. That's the last time, the code was used. The code is quite brute forced and can be improved a lot. I guess you managed to got the core idea of this code. You can improve it by reducing the parameters that are introduced to obtain this particular pattern. Good luck.

Alright thanks!!

**Comment by vigneshrajap** [comment]
>   But is it not being reset inside the RANSAC loop, due to where it is placed? The `}` that ends the RANSAC for loop is placed right below `best_no_inliers`, so at every iteration, it is reset to 0 instead of keeping the previous best value.

Yes you are right. I just got lucky then :smiley:
